services:

  col-qwen-llm:
    build:
      context: .
      dockerfile: src/ColQwenLLM/Dockerfile
    restart: unless-stopped
    runtime: nvidia  # указание на использование NVIDIA runtime
    environment:
        - NVIDIA_VISIBLE_DEVICES=all  # делать все GPU доступными для контейнера
    ports:
      - "8001:8001"

    command: ["uvicorn", "ColQwenLLM.api.main:app", "--host", "0.0.0.0", "--port", "8001"]
    volumes:
      - ./src/ColQwenLLM/:/opt/app-root/src/ColQwenLLM:rw
      - ./src/document_utils/:/opt/app-root/src/document_utils:rw
      - ./cache_hub/clpl/:/opt/app-root/cache_hub/clpl:rw


  milvus-db:
    build:
      context: .
      dockerfile: src/milvus_db/Dockerfile
    restart: unless-stopped
    ports:
      - "8000:8000"
    command: [ "uvicorn", "milvus_db.api.main:app", "--host", "0.0.0.0", "--port", "8000", "--reload"]
    volumes:
      - ./src/milvus_db/:/opt/app-root/src/milvus_db:rw
      - ./src/document_utils/:/opt/app-root/src/document_utils:rw
      - ./milvus_data/:/opt/app-root/milvus_data:rw

#sudo docker compose -f docker-compose.yaml -p autopatent-back up --build milvus-db
