services:
  col-qwen-llm:
    build:
      context: .
      dockerfile: src/ColQwenLLM/Dockerfile
    restart: unless-stopped
    runtime: nvidia  # указание на использование NVIDIA runtime
    environment:
        - NVIDIA_VISIBLE_DEVICES=all  # делать все GPU доступными для контейнера
    ports:
      - "8000:8001"  # Проброс порта 8001 контейнера на 8000 хоста
    command: ["uvicorn", "ColQwenLLM.api.main:app", "--host", "0.0.0.0", "--port", "8001"]
    volumes:
      - ./src/ColQwenLLM/:/opt/app-root/src/ColQwenLLM:rw
      - ./src/document_utils/:/opt/app-root/src/document_utils:rw
      - ./models/:/opt/app-root/models:rw
      - ./cache_hub/clpl/:/opt/app-root/cache_hub/clpl:rw
