import io
from typing import List

import PIL.Image
from fastapi.responses import FileResponse
from fastapi import APIRouter, UploadFile, Depends

import milvus_db.domain.processor as pr
from document_utils.doc_parsers import bytes_to_images
from milvus_db.api.dependencies import get_client_session, get_milvus_client


milvus_router = APIRouter(
    prefix="/milvus_router",
    tags=["milvus"],
)


@milvus_router.get(
    "/db_info",
)
async def get_db_info(
        session = Depends(get_client_session),
        db_client = Depends(get_milvus_client)
):
    return 'Пока нан'


@milvus_router.post(
    "/insert_image",# Set what the media type will be in the autogenerated OpenAPI specification.
    # fastapi.tiangolo.com/advanced/additional-responses/#additional-media-types-for-the-main-response
)
async def insert_images(
    files: List[UploadFile],
    collection_name: str = 'test',
    session = Depends(get_client_session),
    db_client = Depends(get_milvus_client)
):
    images = [PIL.Image.open(io.BytesIO(await im.read())) for im in files]

    result = await pr.insert_images_to_collection(session, db_client, collection_name, images)

    return result

@milvus_router.post(
    "/insert_pdf",
)
async def insert_pdf(
    file: UploadFile,
    collection_name: str = 'test',
    session = Depends(get_client_session),
    db_client = Depends(get_milvus_client)
):
    request_object_content = await file.read()
    images = bytes_to_images(request_object_content)

    result = await pr.insert_images_to_collection(session, db_client, collection_name, images, file.filename)
    return result

@milvus_router.post(
    "/text_search"
)
async def text_search(
    request: str,
    collection_name: str = 'test',
    session = Depends(get_client_session),
    db_client = Depends(get_milvus_client)
):
    results = await pr.search_texts_data_in_collection(session, db_client, collection_name, request)
    if not results:
        return 'empty collection has been provided'
    print(results)
    return FileResponse(results[0][0][2])